apiVersion: v1
entries:
  ollama:
  - annotations:
      artifacthub.io/category: ai-machine-learning
      artifacthub.io/changes: |
        - kind: changed
          description: upgrade app version to 0.3.11
        - kind: fixed
          description: lifecycle postStart hook wait ollama service before pulling models
        - kind: removed
          description: remove duplicated environment variables already defined in Dockerfile
    apiVersion: v2
    appVersion: 0.3.11
    created: "2024-10-16T15:16:31.872621+02:00"
    description: Get up and running with large language models locally.
    digest: 6389e17ed5da81af54ddb3a6c86ee6b4186917388a46a8015c85f4119679ee85
    home: https://ollama.ai/
    icon: https://ollama.ai/public/ollama.png
    keywords:
    - ai
    - llm
    - llama
    - mistral
    kubeVersion: ^1.16.0-0
    maintainers:
    - email: contact@otwld.com
      name: OTWLD
    name: ollama
    sources:
    - https://github.com/ollama/ollama
    - https://github.com/otwld/ollama-helm
    type: application
    urls:
    - https://mbtraore.github.io/openwebui-helm-chart/charts/ollama-0.59.0.tgz
    version: 0.59.0
  pipelines:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: alpha
    created: "2024-10-16T15:16:31.873211+02:00"
    description: 'Pipelines: UI-Agnostic OpenAI API Plugin Framework'
    digest: ab13acb3869193ec3fcdea3c0ff59e5ef85d997322bd7b2444cdbfce998709cc
    home: https://github.com/open-webui/pipelines
    icon: https://github.com/open-webui/pipelines/raw/main/header.png
    keywords:
    - llm
    - chat
    - web-ui
    name: pipelines
    sources:
    - https://github.com/open-webui/helm-charts
    - https://github.com/open-webui/pipelines/pkgs/container/pipelines
    urls:
    - https://mbtraore.github.io/openwebui-helm-chart/charts/pipelines-0.0.4.tgz
    version: 0.0.4
generated: "2024-10-16T15:16:31.870178+02:00"
